<?php

namespace app\modules\admin\controllers;

use yii\web\Controller;

/**
 * Default controller for the `admin` module
 */
class DefaultController extends Controller
{
    public $user_id=0;
    public $user_name=0;
    protected $ignore_action = 'admin/index/login;admin/index/captcha';

    public function behaviors()
    {
        $session = \yii::$app->session;
        //开启session
        $session->open();
        $behaviors = parent::behaviors(); // TODO: Change the autogenerated stub
        //当前路由
        //登录信息
        $admin_user_info = $session->get('admin_user_info');
        $current_route = \yii::$app->requestedRoute;
        if(strpos($this->ignore_action,$current_route)===false && (!$session->isActive || empty($admin_user_info))){
            $this->redirect(\yii\helpers\Url::to(['index/login']));
        }
        $this->user_id = $admin_user_info['user_id'];
        $this->user_name = $admin_user_info['name'];

        return $behaviors;
    }
//    /**
//     * Renders the index view for the module
//     * @return string
//     */
//    public function actionIndex()
//    {
//        return $this->render('index');
//    }
//
    public function actionTest()
    {
        return $this->render('test');
    }
    public function actionError()
    {
        return 'error';
    }
}
