<?php

namespace app\controllers;


use yii\helpers\Url;
use yii\web\Controller;

class CommonController extends Controller
{
    public $layout = 'mobile';
    /**
     * @var \yii\web\Request
     * */
    public $request;

    public $user_id = 0;
    public $is_need_login = true;
    protected $ignore_action = '';


    /*
     * 初始方式
     * */
    public function init()
    {
        $this->request = \Yii::$app->request;

        $user_info = \Yii::$app->session->get('user_info');
        if(!empty($user_info)){
            $this->user_id = $user_info['user_id'];
        }

    }

    public function behaviors()
    {
        $behaviors = parent::behaviors(); // TODO: Change the autogenerated stub
        if(!$this->user_id && strpos($this->ignore_action,\Yii::$app->controller->action->id)===false){
            //需要登录才能访问
            $this->redirect(Url::to(['index/login']));
        }
        return $behaviors;
    }


}
