<?php
namespace app\models;

use yii\db\ActiveRecord;

class UserComplaint extends BaseModel
{
    const SCENARIO_COMPLAINT = 'complaint';

    public static function tableName()
    {
        return '{{%user_complaint}}';
    }


    public function attributeLabels()
    {
        return [
            'uid' => '投诉者',
            'c_uid' => '被投诉者',
            'content' => '内容',
        ];
    }

    public function scenarios()
    {
        $scenarios = parent::scenarios();
        $scenarios[self::SCENARIO_COMPLAINT] = ['uid', 'c_uid','content','img'];
        return $scenarios;
    }

    public function rules()
    {
        $scenario = $this->getScenario();
        if($scenario==self::SCENARIO_COMPLAINT){
            return [
                [['uid'],'required','message'=>'{attribute}信息异常'],
                [['c_uid'],'required','message'=>'{attribute}信息异常'],
                [['content'],'required','message'=>'{attribute}不能为空'],
                [['content'], 'string','length'=>[6,255],'tooLong'=>'{attribute}不得超过{max}个字符','tooShort'=>'{attribute}不得低于{min}个字符'],
            ];
        }else{
            return parent::rules(); // TODO: Change the autogenerated stub
        }
    }

    /*
     * 关联投诉者
     * */
    public function getLinkUser()
    {
        return $this->hasOne(User::className(),['id'=>'uid']);
    }

    /*
     * 关联被投诉者
     * */
    public function getLinkCoverUser()
    {
        return $this->hasOne(User::className(),['id'=>'c_uid']);
    }

}