<?php
namespace app\models;

class UserWithdraw extends BaseModel
{
    //发布
    const SCENARIO_UP = 'up';
    //用户元宝数量
    public $my_money=0;
    public static function tableName()
    {
        return '{{%user_withdraw}}';
    }


    public function attributeLabels()
    {
        return [
            'uid' => '发布者',
            'money' => '额度',
            'price' => '单价',
            'label' => '支付方式',
        ];
    }

    public function scenarios()
    {
        $scenarios = parent::scenarios();
        $scenarios[self::SCENARIO_UP] = ['uid', 'money','price','label','my_money'];
        return $scenarios;
    }

    public function rules()
    {

        $money_name = \Yii::$app->params['money_name'];
        $scenario = $this->getScenario();
        if($scenario==self::SCENARIO_UP){
            return [
                [['uid'],'required','message'=>'{attribute}信息异常'],
                [['money','price','label'],'required','message'=>'{attribute}信息异常'],
                ['money','integer','min'=>0,'tooSmall'=>'{attribute}不得低于{min}'],
                ['money','compare','compareAttribute'=>'my_money','operator'=>'<=','message'=>'出售'.$money_name.'数量必须小于拥有数量'],
                ['price', 'number','min'=>0,'max'=>100,'tooBig'=>'{attribute}不能超过{max}','tooSmall'=>'{attribute}不能低于{min}','message'=>'{attribute}必须是正数'],
                ['label', 'in','range' => [1, 2, 3],'message'=>'{attribute}选择异常'],
            ];
        }else{
            return parent::rules(); // TODO: Change the autogenerated stub
        }


    }

    public function getUserInfo()
    {
        return $this->hasOne(User::className(),['id'=>'uid']);
    }

}